### PR TITLE
Integrated PDF capabilities

### PR DESCRIPTION
**Pull request by ayushmorbar**
## Current behavior
- Now supports text and pdf file processing (txt, pdf)

## Proposed changes
- Integrated PyMuPDF for PDF parsing, allowing text extraction from PDF files.
- Enhanced code to seamlessly handle text and PDF files in user interaction.

## Checks
- Ensured compatibility with existing file types.
- Updated requirements.txt with PyMuPDF library version 1.23.16 for easy dependency installation

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by neokd** [comment]
@ayushmorbar you can use PDFMiner Loader. Since thats common in the repo and used. Instead of adding one more dependency.

**Comment by ayushmorbar** [comment]
Alright, lemme change that then.

**Comment by ayushmorbar** [comment]
> @ayushmorbar you can use PDFMiner Loader. Since thats common in the repo and used. Instead of adding one more dependency.

I've made the changes as asked in the code.

**Comment by neokd** [comment]
Thanks for your contribution @ayushmorbar

**Comment by ayushmorbar** [comment]
Appreciated 🙌

**Pull request merged**
