### PR TITLE
implementation of notification function

### LINKED ISSUE #131: Notification from system
Create a file in` neogpt/utils/notify.py` in the project and create a function called notify which accepts 2 parameters i.e **title, message** to send notification to user. 

Note: the function should send system level notification and should be cross platform (windows, macOS, Linux).

### PR DESCRIPTION
**Pull request by n0n3br**
## Current behavior

- there isn't a function to add system notifications to user

## Proposed changes

- fix #131 - create  neogpt/utils/notify.py file in the project and create a function called notify which accepts 2 parameters i.e title, message to send cross platform system notification to user.

## Checks

- [ ] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by neokd** [comment]
@n0n3br Can you share a screenshot?

**Comment by neokd** [comment]
@n0n3br thanks for your contribution. Is this contribution under the jwoc contest?

**Comment by n0n3br** [comment]
No, it's not.

**Comment by neokd** [comment]
Okkayy

**Comment by n0n3br** [comment]
You're welcome.

**Pull request merged**
