### PR TITLE
openai_support added

### PR DESCRIPTION
**Pull request by rahim-khan-iitg**
Now we can use OpenAI as LLM . first of all specify your openai api key in ``` .env ```  file with the name ``` OPENAI_API_KEY="type your key" ``` . To use it type command ``` python main.py --model_type openai ```

### CODE REVIEW

**Comment by neokd** [comment]
Can you attach screen shot of it working?

**Comment by rahim-khan-iitg** [comment]
My open ai key exhausted

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by neokd** [comment]
Thanks for the contribution for CodePeak 2k23. Merging the PR

**Comment by rahim-khan-iitg** [comment]
Qdrant is also waiting to be merged

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by neokd** [comment]
I'll chech the entire code and merge it

**Pull request merged**
