### PR TITLE
added only_llm mode in cli mode

### PR DESCRIPTION
**Pull request by rahim-khan-iitg**
to run it in only_llm mode type python main.py --mode llm_only i was adding it in ui mode also but someone already working on it.

## Current behavior
currently we can not run it in only llm mode 

## Proposed changes
i have added chat support for only llm mode

## Checks

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by neokd** [comment]
and bhai 80 file changes? 🙄

**Comment by rahim-khan-iitg** [comment]
I have only added 2-3 files. Git itself added .md files and other files I don't know why

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by neokd** [comment]
I have marked the changes. You can create update the PR with those files and changes.

**Comment by rahim-khan-iitg** [comment]
i am making a new fork i will add those changes then i will do a new PR. For now i m closing this PR.

**Pull request closed without merging**
