### PR TITLE
fix: fix python version to have the docker build working

### LINKED ISSUE #79: Docker: Unable to build the docker image.
Unable to run the docker image properly. It gives error when installing the requirements
Screenshot 2023-10-31 at 1 45 07 AM

### PR DESCRIPTION
**Pull request by ha36d**
resolves #79
Last version of torch is not compatible with python >= 3.12, therefore the version of python is fixed to 3.11. Bump auto-gptq to the latest version, as there was bugs.

### CODE REVIEW

**Comment by neokd** [comment]
Does it work after bumping auto-gptq?

**Comment by ha36d** [comment]
> Does it work after bumping auto-gptq?

Yes.

**Comment by ha36d** [comment]
Done.

**Comment by neokd** [comment]
@hamed thanks for the contribution

**Comment by neokd** [comment]
@ha36d  the issue still persist when i run.
Can you provide the commands to run properly?

**Comment by ha36d** [comment]
> @ha36d the issue still persist when i run. Can you provide the commands to run properly?

@neokd for me, it is working with the following command:
`docker build -f Dockerfile . -t neogpt`
It takes time, but finishes successfully.

**Comment by neokd** [comment]
Is there any requirement to upgrade python ? in the container?

**Comment by neokd** [comment]
It says auto-gptq 0.4.2 not found

**Comment by ha36d** [comment]
It seems some cache issues. can you please delete the docker images and layers related to this neogpt?

**Comment by ha36d** [comment]
also I see that `dev-requirement.txt` is renamed to `dev-requirements.txt` without chaning the references in dockerfile.

**Comment by neokd** [comment]
No currently we don't have a docker repository. Is there any other way to run it locally?

**Comment by ha36d** [comment]
No, I guess there is an environment issue, as the pip is up to date, the version 0.4.2 of auto-gptq exists.

**Comment by neokd** [comment]
How can we fix it?

**Comment by ha36d** [comment]
As I said, I think it is your local env that has an issue. I proposed to have a docker build (even without push) pipeline to show you that it works well in Github Actions.

**Comment by neokd** [comment]
Yeah you can create an issue and work on it

**Comment by ha36d** [comment]
> Yeah you can create an issue and work on it

https://github.com/neokd/NeoGPT/issues/87

**Pull request merged**
