### PR TITLE
Write Logs to a File

### PR DESCRIPTION
**Pull request by y9rabbito**
This is regarding the issue #67 modify builder.py to logged info in a file named "log_file.log"

### CODE REVIEW

**Comment by neokd** [comment]
@y9rabbito can u rename the file name to builder.log and store it

**Comment by y9rabbito** [comment]
Okk @neokd

**Comment by y9rabbito** [comment]
@neokd i have changed the filename, take a look and see if it's can be merged

**Comment by neokd** [comment]
@y9rabbito sure

**Comment by y9rabbito** [comment]
Thank you @neokd

**Pull request merged**
