### PR TITLE
feat: created neogpt.sh shell script for easy execution

### PR DESCRIPTION
**Pull request by bryce-seefieldt**
Here's a working solution for [Issue 43](https://github.com/neokd/NeoGPT/issues/43).
Let me know if you seen any issues or if I can improve how it works for the desired purpose. Thanks for the opportunity to contribute.

### CODE REVIEW

**Comment by neokd** [comment]
Can you also add support for python venv?

**Comment by neokd** [comment]
@bryce-seefieldt Thanks for the contribution.

**Comment by bryce-seefieldt** [comment]
> @bryce-seefieldt Thanks for the contribution.

My pleasure, happy to be able to help.

**Comment by bryce-seefieldt** [comment]
> Can you also add support for python venv?

I can definitely work on that.  Just going to be a few days before I get started as a few other projects I'm working on need to be wrapped up asap.  I'll let you knkow once I get started.

**Pull request merged**
