### PR TITLE
Containerizing NeoGPT and appropriate Doc updates.

### LINKED ISSUE #48: Docker
Implement Docker support to make it easier for users to deploy and run NeoGPT in various environments. Dockerization ensures consistent and isolated runtime environments, simplifying the setup process and enhancing portability.

Tasks:

1. Create a Dockerfile for NeoGPT.
2. Define the base image and required dependencies.
3. Configure the container to run NeoGPT with specific command-line arguments.
4. Provide clear instructions for building and running NeoGPT using Docker.

### PR DESCRIPTION
**Pull request by zakhaev26**
(Fixes #48)
This PR adds detailed documentation and incorporates steps for building the database within the Dockerfile. The documentation [TBD] provides clear instructions for users to build the database, including creating the `builder.url` file, adding YouTube video URLs, and running the `builder.py` script. By including these steps in the Dockerfile, the image will automatically build the necessary database when the container is initiated. These changes aim to improve the user experience and streamline the process of setting up the database within the Docker environment.

### CODE REVIEW

**Comment by neokd** [comment]
@zakhaev26 can you provide commands to run so I can latwr append it in the readme

**Comment by zakhaev26** [comment]
Yeah,just a few more fixes and the PR is good to go!
I will provide a documentation in Comment. Let me know whether you want me to directly append that in README.md or not!

**Comment by zakhaev26** [comment]
Also , I didn't include assets and other redundant files in the Image as it would unnecessarily make the image large in terms of size.
Do let me know if this works

**Comment by neokd** [comment]
@zakhaev26  Thanks for your contribution. I'll merge. Also can you help for further extending with docker?

**Comment by zakhaev26** [comment]
> @zakhaev26 Thanks for your contribution. I'll merge the PR. Also can you help for further extending with docker?

Glad i could be of help. I beleive that the current latest version of python isn't compatible with pytorch (from #81) , that I guess has been fixed.

**Comment by neokd** [comment]
@zakhaev26 it still gives error. Can't figure out what is the issue

**Comment by zakhaev26** [comment]
Okay,I am looking into it!

**Pull request merged**
