### PR TITLE
docs: fixed typo Line 49 of README.md

### PR DESCRIPTION
**Pull request by bryce-seefieldt**
Noticed a missing "s" in README.md; Line 49 "dev-requirements.txt"

### CODE REVIEW

**Comment by neokd** [comment]
it should actually be requirements.txt and now dev-requirements.txt Since dev is for docker as of now

**Comment by neokd** [comment]
You can update the readme to `pip install -r requirements.txt`

**Comment by bryce-seefieldt** [comment]
> You can update the readme to `pip install -r requirements.txt`

Updated: [2d8dd1e](https://github.com/bryce-seefieldt/NeoGPT/commit/2d8dd1ec85ec9e28758e288ad233a91f8174f8cd)

**Comment by neokd** [comment]
@bryce-seefieldt Thanks for the change. Didn't notice that 🤣

**Pull request merged**
