### PR TITLE
Added documentation in card format for llms in introduction.mdx

### PR DESCRIPTION
**Pull request by Saloni0512**
## Checks

- [ x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by neokd** [comment]
Can you remove the virtual env. You have added that in the commit

**Comment by Saloni0512** [comment]
is there any way to remove the virtual env all at once because
there are too many files

**Comment by neokd** [comment]
You can delete the folder

**Comment by Saloni0512** [comment]
I have made the changes. Please review them

**Pull request merged**
