### PR TITLE
Add /history command to display chat history

### PR DESCRIPTION
**Pull request by ayushmorbar**
## Current behavior
- Currently, the program supports three commands: "/reset", "/exit", and "/history". The "/reset" command resets the chat session, the "/exit" command shuts down the program, and the "/history" command prints the chat history. If an unrecognized command is entered, the program prints an error message.

## Proposed changes
- The proposed changes include the addition of a new command "/history". This command, when invoked, prints out the chat history for the current session.

## Checks
- The checks in this code are primarily conditional checks to determine which command the user has entered. If the user enters "/reset", the chat session is reset. If "/exit" is entered, the program shuts down. If "/history" is entered, the chat history is printed. If none of these commands are entered, an error message is printed.
- Ensured compatibility with existing file types.
- The code follows the project's coding style guidelines.

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by ayushmorbar** [comment]
#137 refer

**Comment by ayushmorbar** [comment]
Do not merge the commit where I deleted the notify.py script file completely in pursuit of removing the part of the code, or if possible delete the commit or pull request so I can start clean.

Refer to this issue and assign me, so i can make it right quick. https://github.com/neokd/NeoGPT/issues/138#issuecomment-1922215502

**Comment by neokd** [comment]
Can you create a new PR

**Comment by ayushmorbar** [comment]
yeah okay! Lemme do it

**Pull request closed without merging**
