### PR TITLE
Implementing the export config functionality properly

### PR DESCRIPTION
**Pull request by yashasvini121**
## Current behavior

The code doesn't work correctly if the directory doesn't exist.
## Proposed changes

This PR resolves issue #193.
## Checks
- Correcting the export_cofig function
- Adding the magic function for `/export`

- [x] All commits in this Pull Request are [signed](https://docs.github.com/en/authentication/managing-commit-signature-verification/signing-commits) and Verified by Github.

### CODE REVIEW

**Comment by neokd** [comment]
You have magic commands

**Comment by yashasvini121** [comment]
Sorry, let me check

**Comment by yashasvini121** [comment]
I will correct that, sorry

**Comment by yashasvini121** [comment]
Please review my PR again

**Comment by neokd** [comment]
There are more field to add when exporting the config.

> You have removed all the magic commands. Also, the config was updated and many fields are not been writtern into the config add them also

**Comment by yashasvini121** [comment]
Ok, I will add them.

**Comment by yashasvini121** [comment]
@neokd, Please check again

**Pull request merged**
