### PR TITLE
streamlit ui_enhancements

### PR DESCRIPTION
**Pull request by rahim-khan-iitg**
Now all the available models can be loaded dynamically in ui mode and all the available db can be loaded dynamically . I have not touched the file handling in ui. llm_only mode is also supported in ui
image

### CODE REVIEW

**Comment by rahim-khan-iitg** [comment]
Wait do not merge it there is some issue. Let me verify it first

**Comment by neokd** [comment]
You can directly pass UI args into the function rather than writing a JSON.

**Comment by rahim-khan-iitg** [comment]
How?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by neokd** [comment]
As function params

**Comment by rahim-khan-iitg** [comment]
if args.ui:
        with open(UI_ARGS_PATH,'w') as file:
            json.dump(UI_ARGS,file)
        logging.info("Starting the UI server for NeoGPT 🤖")
        logging.info("Note: The UI server only supports local retriever and Chroma DB")
        sys.argv = ["streamlit", "run", "neogpt/ui.py"]
        sys.exit(stcli.main())


where to pass those arguments i m not getting😒

**Comment by neokd** [comment]
The one which ur passing the ui_args.json are already present in the config.py then y you have to pass a separate file?

**Comment by rahim-khan-iitg** [comment]
Those are the defaults i should not mess with them🙄

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Pull request merged**
