### PR TITLE
Add conversation loading functionality to chatbot

### PR DESCRIPTION
**Pull request by ayushmorbar**
This pull request adds conversation loading functionality to the chatbot. It includes a new function `load_conversations()` that retrieves conversation files from the `neogpt/conversations` directory. The `--conversation` flag has been added to the command line interface to enable loading conversations into the chatbot.

#### refer #190

NOTE:
the code might not be perfect and there will be some mistakes, i might've done and so i want you to correct me- if there's!

### CODE REVIEW

**Comment by neokd** [comment]
Can you move the load_conversations from main.py to manager.py? because it should read the file and load it directly into the memory of the chain.

**Comment by ayushmorbar** [comment]
okay, i am on it.

**Comment by ayushmorbar** [comment]
NOTE: The import files got formatted due to RUFF, so nothing is changed or modified except the part of importing the conversations_navigators.py function i.e., load_conversations().

**Comment by neokd** [comment]
This should not be like this. The conversation_navigator should load the files from the conversation dir and should should show all the available files in the dir. If a user select a file then that file should be loaded into the history

**Comment by neokd** [comment]
Any updates on this?

**Comment by ayushmorbar** [comment]
Yeah, I get it and also I guess I've confused myself on this issue, though I've made the essential changes as required… Do take a review of that, point out the wrongdoings.

**Comment by neokd** [comment]
You can put all the code for navigation everything into the conversation_navigator file. Stuff like navigating and loading the file etc. In manager function in manager.py you can pass a chain and load the file into the chain.

**Comment by ayushmorbar** [comment]
hey, i think i will pass this issue and will try it later, if its still live.

**Comment by neokd** [comment]
okayy

**Pull request closed without merging**
